

set(VMMLIB_PACKAGE_VERSION 1.7.0)
set(VMMLIB_REPO_URL https://github.com/VMML/vmmlib.git)
#set(VMMLIB_REPO_TAG 1.4)
set(VMMLIB_DEPENDS REQUIRED OpenMP OPTIONAL LAPACK CBLAS)
set(VMMLIB_FORCE_BUILD ${CI_BUILD})

if(CI_BUILD_COMMIT)
  set(VMMLIB_REPO_TAG ${CI_BUILD_COMMIT})
else()
  set(VMMLIB_REPO_TAG master)
endif()
set(VMMLIB_FORCE_BUILD ON)
set(VMMLIB_SOURCE ${CMAKE_SOURCE_DIR})